### ISSUE TITLE
Some libraries trigger paramSpec must not be null for ECDSA

### ISSUE THREAD

**Issue by quapka** [crocs-muni/ECTester#23]
The command `java -jar standalone/build/libs/ECTesterStandalone.jar ecdsa -n 10 -t NONEwithECDSA  openssl` works, but for `nettle` it doesn't work:

```
$ java -jar standalone/build/libs/ECTesterStandalone.jar ecdsa -n 10 -t NONEwithECDSA  nettle
index;signTime[nano];verifyTime[nano];data;pubW;privS;signature[NONE];nonce;verified
java.security.spec.InvalidParameterSpecException: paramSpec must not be null
        at java.base/sun.security.util.ECParameters.engineInit(ECParameters.java:107)
        at java.base/java.security.AlgorithmParameters.init(AlgorithmParameters.java:294)
        at cz.crcs.ectester.standalone.libs.jni.NativeSignatureSpi$Nettle.sign(NativeSignatureSpi.java:582)
        at cz.crcs.ectester.standalone.libs.jni.NativeSignatureSpi$SimpleSignatureSpi.engineSign(NativeSignatureSpi.java:78)
        at java.base/java.security.Signature$Delegate.engineSign(Signature.java:1404)
        at java.base/java.security.Signature.sign(Signature.java:713)
        at cz.crcs.ectester.standalone.ECTesterStandalone.ecdsa(ECTesterStandalone.java:642)
        at cz.crcs.ectester.standalone.ECTesterStandalone.run(ECTesterStandalone.java:164)
        at cz.crcs.ectester.standalone.ECTesterStandalone.main(ECTesterStandalone.java:846)
Exception in thread "main" java.lang.NullPointerException
        at cz.crcs.ectester.standalone.libs.jni.NativeECPublicKey$ANSIX962.getW(NativeECPublicKey.java:54)
        at cz.crcs.ectester.standalone.libs.jni.NativeECPublicKey$Nettle.getW(NativeECPublicKey.java:179)
        at cz.crcs.ectester.standalone.libs.jni.NativeECPublicKey$ANSIX962.getData(NativeECPublicKey.java:63)
        at cz.crcs.ectester.standalone.libs.jni.NativeECPublicKey$Nettle.getData(NativeECPublicKey.java:179)
        at cz.crcs.ectester.standalone.libs.jni.NativeSignatureSpi$SimpleSignatureSpi.engineVerify(NativeSignatureSpi.java:85)
        at java.base/java.security.Signature$Delegate.engineVerify(Signature.java:1416)
        at java.base/java.security.Signature.verify(Signature.java:790)
        at cz.crcs.ectester.standalone.ECTesterStandalone.ecdsa(ECTesterStandalone.java:652)
        at cz.crcs.ectester.standalone.ECTesterStandalone.run(ECTesterStandalone.java:164)
        at cz.crcs.ectester.standalone.ECTesterStandalone.main(ECTesterStandalone.java:846)

```
At least from the output of `list-libs` it seems like it should be supported:
```
 - Nettle
                - Fullname: Nettle
                - Version: 3.9
                - Supports native timing: [cputime-processor, cputime-thread, monotonic, monotonic-raw, rdtsc]
                - KeyPairGenerators: EC
                - KeyAgreements: ECDH
                - Signatures: NONEwithECDSA
                - Curves: secp192r1, secp224r1, secp256r1, secp384r1, secp521r1
```
Maybe a correct curve needs to be input from the CLI?

**Comment by J08nY** [comment]
This is not a CLI problem. This is a known thing :) See the tests which exclude Nettle for this very reason. There is also a TODO in Nettle code to properly handle this. Thanks for documenting this here though, we can dedide on a solution that works, as this will also be relevant for the TropicSquare impl.

The TLDR is: Nettle only supports named curves, yet ECPublic/ECPrivateKey instances need to have ECParameterSpec `.params` in them. As the Nettle implementation does weird hacky stuff with the input params in keygen and ECDH/ECDSA, it does not set these on the key objects, hence this error.

I am not sure what the correct solution is. I think the Nettle impl (and also the TropicSquare impl and any that support only named cures) should have:
 - excplicit curve -> named curve mapping when going into the library (by basically comparing the given parameters to the named curve looked up in the EC_Store),
 - named curve -> ECParameterSpec mapping when going out of the library (as into the ECPrivateKey/ECPublicKey), by looking up the explicit params in the EC_Store.

This will honor the JCA API contract and should fix this.
